On branch main Your branch is up to date with 'origin/main'.
Changes to be committed:
	deleted:    .errlog
	modified:   .gitignore
	modified:   setup.sh
	modified:   zEnv
	deleted:    zshrc.bak

diff --git a/zEnv b/zEnv
--- a/zEnv
+++ b/zEnv
@@ -27,8 +27,16 @@ function source_dotenv() {
   local dev_env_file="${HOME}/.config/development/environment/dotenv/.env"
   local local_env_file="${ZDOTDIR}/.env"
    if [[ -f "${dev_env_file}" ]]; then
-    cp "${dev_env_file}" "${local_env_file{,."$(date +%Y%m%d-%H%M%S)"}}"
-    source "${local_env_file}"
+    cp -p "${dev_env_file}" "${local_env_file}.bak.$(date +%Y%m%d-%H%M%S)"
+    if source "${local_env_file}"; then
+      echo "Sourced ${local_env_file}"
+    else
+      echo "Failed to source ${local_env_file}"
+      exit 1
+    fi
+  else
+    echo "${dev_env_file} not found"
+    exit 1
 fi 
 }
 source_dotenv
